### ISSUE TITLE
Inaccurate command in README.md

### ISSUE THREAD

**Issue by ddmatsu** [bn222/bluefield-2-tools#13]
README tells to use the following command to launch the tools.
`sudo podman exec -it bf <TOOL_NAME>`
I think '/' should be added before <TOOL_NAME> since the scripts are in '/',  but the directory is not configured in $PATH.
Perhaps it is possible to modify the environment variable using Dockerfile, but I am not sure.

> [root@host105 /]# pwd; ls
> /
> '=2.12.0'         FETCH_HEAD   __pycache__   boot                        common_bf.py   dev          fwversion   index                lib      lost+found   opt           refs       run        sys   workflows
>  AUTO_MERGE       HEAD         afs           branches                    config         etc          get_mode    index.stash.346698   lib64    media        packed-refs   reset      sbin       tmp
>  COMMIT_EDITMSG   ORIG_HEAD    bfb           common_bf.cpython-310.pyc   console        fwdefaults   home        info                 listbf   mnt          proc          root       set_mode   usr
>  Dockerfile       README.md    bin           common_bf.cpython-311.pyc   description    fwup         hooks       kickstart.ks         logs     objects      pxeboot       rshim.sh   srv        var
> [root@host105 /]# echo $PATH
> /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by bn222** [comment]
You're right. Pedantically, a `/` is needed.
