### ISSUE TITLE
listbf tool does not work

### ISSUE THREAD

**Issue by ddmatsu** [bn222/bluefield-2-tools#14]
In listbf:
```
#!/usr/bin/env python3
import common_bf

def main():
    bf2s = common_bf.find_bf2_pci_addresses()
```
find_bf2_pci_addresses() was renamed to be find_bf_pci_addresses(), but it seems listbf was overlooked.
cf https://github.com/bn222/bluefield-2-tools/commit/1195026b90916b43e4d54f35ebbe66a3cb2721b5

Does this repository accepts PRs to fix this kind of issues,
or is this tool private to Red Hat people?

**Comment by bn222** [comment]
This repo is open to the world and accepts PRs. Looking forward to your contribution!

**Comment by ddmatsu** [comment]
Opened a PR to fix this issue along with other problems in pxeboot.
cf https://github.com/bn222/bluefield-2-tools/pull/15
